//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// C п р материалы.
    /// </summary>
    // *** Start programmer edit section *** (CПРМатериалы CustomAttributes)

    // *** End programmer edit section *** (CПРМатериалы CustomAttributes)
    [AutoAltered()]
    [Caption("C п р материалы")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CПРМатериалыE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "СПРСклад as \'С п р склад\'",
            "СПРСклад.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "СПРСклад.Наименование"})]
    [MasterViewDefineAttribute("CПРМатериалыE", "СПРСклад", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("CПРМатериалыL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "СПРСклад.Наименование as \'Склад\'"})]
    public class CПРМатериалы : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private IIS.Kursovaya_Gladkov.СПРСклад fСПРСклад;
        
        // *** Start programmer edit section *** (CПРМатериалы CustomMembers)

        // *** End programmer edit section *** (CПРМатериалы CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (CПРМатериалы.ID CustomAttributes)

        // *** End programmer edit section *** (CПРМатериалы.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (CПРМатериалы.ID Get start)

                // *** End programmer edit section *** (CПРМатериалы.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (CПРМатериалы.ID Get end)

                // *** End programmer edit section *** (CПРМатериалы.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CПРМатериалы.ID Set start)

                // *** End programmer edit section *** (CПРМатериалы.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (CПРМатериалы.ID Set end)

                // *** End programmer edit section *** (CПРМатериалы.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (CПРМатериалы.Наименование CustomAttributes)

        // *** End programmer edit section *** (CПРМатериалы.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (CПРМатериалы.Наименование Get start)

                // *** End programmer edit section *** (CПРМатериалы.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (CПРМатериалы.Наименование Get end)

                // *** End programmer edit section *** (CПРМатериалы.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CПРМатериалы.Наименование Set start)

                // *** End programmer edit section *** (CПРМатериалы.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (CПРМатериалы.Наименование Set end)

                // *** End programmer edit section *** (CПРМатериалы.Наименование Set end)
            }
        }
        
        /// <summary>
        /// C п р материалы.
        /// </summary>
        // *** Start programmer edit section *** (CПРМатериалы.СПРСклад CustomAttributes)

        // *** End programmer edit section *** (CПРМатериалы.СПРСклад CustomAttributes)
        [PropertyStorage(new string[] {
                "СПРСклад"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov.СПРСклад СПРСклад
        {
            get
            {
                // *** Start programmer edit section *** (CПРМатериалы.СПРСклад Get start)

                // *** End programmer edit section *** (CПРМатериалы.СПРСклад Get start)
                IIS.Kursovaya_Gladkov.СПРСклад result = this.fСПРСклад;
                // *** Start programmer edit section *** (CПРМатериалы.СПРСклад Get end)

                // *** End programmer edit section *** (CПРМатериалы.СПРСклад Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (CПРМатериалы.СПРСклад Set start)

                // *** End programmer edit section *** (CПРМатериалы.СПРСклад Set start)
                this.fСПРСклад = value;
                // *** Start programmer edit section *** (CПРМатериалы.СПРСклад Set end)

                // *** End programmer edit section *** (CПРМатериалы.СПРСклад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CПРМатериалыE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CПРМатериалыE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CПРМатериалыE", typeof(IIS.Kursovaya_Gladkov.CПРМатериалы));
                }
            }
            
            /// <summary>
            /// "CПРМатериалыL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CПРМатериалыL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CПРМатериалыL", typeof(IIS.Kursovaya_Gladkov.CПРМатериалы));
                }
            }
        }
    }
}
