//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док чертеж.
    /// </summary>
    // *** Start programmer edit section *** (ДокЧертеж CustomAttributes)

    // *** End programmer edit section *** (ДокЧертеж CustomAttributes)
    [AutoAltered()]
    [Caption("Док чертеж")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокЧертежE", new string[] {
            "Дата as \'Дата\'",
            "НомерЧертежа as \'Номер чертежа\'",
            "Утверждение as \'Утверждение\'",
            "ТЧзаявка.НомерДетали",
            "ТЧзаявка.НаименДетали as \'Наимен детали\'",
            "ТЧзаявка.CПРМатериалы.Наименование"}, Hidden=new string[] {
            "ТЧзаявка.НаименДетали"})]
    [View("ДокЧертежL", new string[] {
            "Дата as \'Дата\'",
            "НомерЧертежа as \'Номер чертежа\'",
            "Утверждение as \'Утверждение\'",
            "ТЧзаявка.НомерДетали as \'Номер детали\'",
            "ТЧзаявка.НаименДетали as \'Наименование детали\'",
            "ТЧзаявка.CПРМатериалы.Наименование as \'Материал\'"})]
    public class ДокЧертеж : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата;
        
        private int fНомерЧертежа;
        
        private bool fУтверждение;
        
        private IIS.Kursovaya_Gladkov.ТЧзаявка fТЧзаявка;
        
        // *** Start programmer edit section *** (ДокЧертеж CustomMembers)

        // *** End programmer edit section *** (ДокЧертеж CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокЧертеж.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокЧертеж.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокЧертеж.Дата Get start)

                // *** End programmer edit section *** (ДокЧертеж.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокЧертеж.Дата Get end)

                // *** End programmer edit section *** (ДокЧертеж.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЧертеж.Дата Set start)

                // *** End programmer edit section *** (ДокЧертеж.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокЧертеж.Дата Set end)

                // *** End programmer edit section *** (ДокЧертеж.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерЧертежа.
        /// </summary>
        // *** Start programmer edit section *** (ДокЧертеж.НомерЧертежа CustomAttributes)

        // *** End programmer edit section *** (ДокЧертеж.НомерЧертежа CustomAttributes)
        public virtual int НомерЧертежа
        {
            get
            {
                // *** Start programmer edit section *** (ДокЧертеж.НомерЧертежа Get start)

                // *** End programmer edit section *** (ДокЧертеж.НомерЧертежа Get start)
                int result = this.fНомерЧертежа;
                // *** Start programmer edit section *** (ДокЧертеж.НомерЧертежа Get end)

                // *** End programmer edit section *** (ДокЧертеж.НомерЧертежа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЧертеж.НомерЧертежа Set start)

                // *** End programmer edit section *** (ДокЧертеж.НомерЧертежа Set start)
                this.fНомерЧертежа = value;
                // *** Start programmer edit section *** (ДокЧертеж.НомерЧертежа Set end)

                // *** End programmer edit section *** (ДокЧертеж.НомерЧертежа Set end)
            }
        }
        
        /// <summary>
        /// Утверждение.
        /// </summary>
        // *** Start programmer edit section *** (ДокЧертеж.Утверждение CustomAttributes)

        // *** End programmer edit section *** (ДокЧертеж.Утверждение CustomAttributes)
        public virtual bool Утверждение
        {
            get
            {
                // *** Start programmer edit section *** (ДокЧертеж.Утверждение Get start)

                // *** End programmer edit section *** (ДокЧертеж.Утверждение Get start)
                bool result = this.fУтверждение;
                // *** Start programmer edit section *** (ДокЧертеж.Утверждение Get end)

                // *** End programmer edit section *** (ДокЧертеж.Утверждение Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЧертеж.Утверждение Set start)

                // *** End programmer edit section *** (ДокЧертеж.Утверждение Set start)
                this.fУтверждение = value;
                // *** Start programmer edit section *** (ДокЧертеж.Утверждение Set end)

                // *** End programmer edit section *** (ДокЧертеж.Утверждение Set end)
            }
        }
        
        /// <summary>
        /// Док чертеж.
        /// </summary>
        // *** Start programmer edit section *** (ДокЧертеж.ТЧзаявка CustomAttributes)

        // *** End programmer edit section *** (ДокЧертеж.ТЧзаявка CustomAttributes)
        [PropertyStorage(new string[] {
                "ТЧзаявка"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov.ТЧзаявка ТЧзаявка
        {
            get
            {
                // *** Start programmer edit section *** (ДокЧертеж.ТЧзаявка Get start)

                // *** End programmer edit section *** (ДокЧертеж.ТЧзаявка Get start)
                IIS.Kursovaya_Gladkov.ТЧзаявка result = this.fТЧзаявка;
                // *** Start programmer edit section *** (ДокЧертеж.ТЧзаявка Get end)

                // *** End programmer edit section *** (ДокЧертеж.ТЧзаявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЧертеж.ТЧзаявка Set start)

                // *** End programmer edit section *** (ДокЧертеж.ТЧзаявка Set start)
                this.fТЧзаявка = value;
                // *** Start programmer edit section *** (ДокЧертеж.ТЧзаявка Set end)

                // *** End programmer edit section *** (ДокЧертеж.ТЧзаявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокЧертежE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокЧертежE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокЧертежE", typeof(IIS.Kursovaya_Gladkov.ДокЧертеж));
                }
            }
            
            /// <summary>
            /// "ДокЧертежL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокЧертежL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокЧертежL", typeof(IIS.Kursovaya_Gladkov.ДокЧертеж));
                }
            }
        }
    }
}
