//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док заявка.
    /// </summary>
    // *** Start programmer edit section *** (ДокЗаявка CustomAttributes)

    // *** End programmer edit section *** (ДокЗаявка CustomAttributes)
    [AutoAltered()]
    [Caption("Док заявка")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокЗаявкаE", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "ДатаЗаявки as \'Дата заявки\'",
            "СПРКлиент.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "СПРКлиент.Наименование"})]
    [AssociatedDetailViewAttribute("ДокЗаявкаE", "ТЧзаявка", "ТЧзаявкаE", true, "", "Т чзаявка", true, new string[] {
            ""})]
    [View("ДокЗаявкаL", new string[] {
            "НомерЗаявки as \'Номер заявки\'",
            "ДатаЗаявки as \'Дата заявки\'",
            "СПРКлиент.Наименование as \'Клиент\'"})]
    [AssociatedDetailViewAttribute("ДокЗаявкаL", "ТЧзаявка", "ТЧзаявкаE", false, "", "Детали заявки", true, new string[] {
            ""})]
    public class ДокЗаявка : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомерЗаявки;
        
        private System.DateTime fДатаЗаявки;
        
        private IIS.Kursovaya_Gladkov.СПРКлиент fСПРКлиент;
        
        private IIS.Kursovaya_Gladkov.DetailArrayOfТЧзаявка fТЧзаявка;
        
        // *** Start programmer edit section *** (ДокЗаявка CustomMembers)

        // *** End programmer edit section *** (ДокЗаявка CustomMembers)

        
        /// <summary>
        /// ДатаЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (ДокЗаявка.ДатаЗаявки CustomAttributes)

        // *** End programmer edit section *** (ДокЗаявка.ДатаЗаявки CustomAttributes)
        public virtual System.DateTime ДатаЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (ДокЗаявка.ДатаЗаявки Get start)

                // *** End programmer edit section *** (ДокЗаявка.ДатаЗаявки Get start)
                System.DateTime result = this.fДатаЗаявки;
                // *** Start programmer edit section *** (ДокЗаявка.ДатаЗаявки Get end)

                // *** End programmer edit section *** (ДокЗаявка.ДатаЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЗаявка.ДатаЗаявки Set start)

                // *** End programmer edit section *** (ДокЗаявка.ДатаЗаявки Set start)
                this.fДатаЗаявки = value;
                // *** Start programmer edit section *** (ДокЗаявка.ДатаЗаявки Set end)

                // *** End programmer edit section *** (ДокЗаявка.ДатаЗаявки Set end)
            }
        }
        
        /// <summary>
        /// НомерЗаявки.
        /// </summary>
        // *** Start programmer edit section *** (ДокЗаявка.НомерЗаявки CustomAttributes)

        // *** End programmer edit section *** (ДокЗаявка.НомерЗаявки CustomAttributes)
        public virtual int НомерЗаявки
        {
            get
            {
                // *** Start programmer edit section *** (ДокЗаявка.НомерЗаявки Get start)

                // *** End programmer edit section *** (ДокЗаявка.НомерЗаявки Get start)
                int result = this.fНомерЗаявки;
                // *** Start programmer edit section *** (ДокЗаявка.НомерЗаявки Get end)

                // *** End programmer edit section *** (ДокЗаявка.НомерЗаявки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЗаявка.НомерЗаявки Set start)

                // *** End programmer edit section *** (ДокЗаявка.НомерЗаявки Set start)
                this.fНомерЗаявки = value;
                // *** Start programmer edit section *** (ДокЗаявка.НомерЗаявки Set end)

                // *** End programmer edit section *** (ДокЗаявка.НомерЗаявки Set end)
            }
        }
        
        /// <summary>
        /// Док заявка.
        /// </summary>
        // *** Start programmer edit section *** (ДокЗаявка.СПРКлиент CustomAttributes)

        // *** End programmer edit section *** (ДокЗаявка.СПРКлиент CustomAttributes)
        [PropertyStorage(new string[] {
                "СПРКлиент"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov.СПРКлиент СПРКлиент
        {
            get
            {
                // *** Start programmer edit section *** (ДокЗаявка.СПРКлиент Get start)

                // *** End programmer edit section *** (ДокЗаявка.СПРКлиент Get start)
                IIS.Kursovaya_Gladkov.СПРКлиент result = this.fСПРКлиент;
                // *** Start programmer edit section *** (ДокЗаявка.СПРКлиент Get end)

                // *** End programmer edit section *** (ДокЗаявка.СПРКлиент Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЗаявка.СПРКлиент Set start)

                // *** End programmer edit section *** (ДокЗаявка.СПРКлиент Set start)
                this.fСПРКлиент = value;
                // *** Start programmer edit section *** (ДокЗаявка.СПРКлиент Set end)

                // *** End programmer edit section *** (ДокЗаявка.СПРКлиент Set end)
            }
        }
        
        /// <summary>
        /// Док заявка.
        /// </summary>
        // *** Start programmer edit section *** (ДокЗаявка.ТЧзаявка CustomAttributes)

        // *** End programmer edit section *** (ДокЗаявка.ТЧзаявка CustomAttributes)
        public virtual IIS.Kursovaya_Gladkov.DetailArrayOfТЧзаявка ТЧзаявка
        {
            get
            {
                // *** Start programmer edit section *** (ДокЗаявка.ТЧзаявка Get start)

                // *** End programmer edit section *** (ДокЗаявка.ТЧзаявка Get start)
                if ((this.fТЧзаявка == null))
                {
                    this.fТЧзаявка = new IIS.Kursovaya_Gladkov.DetailArrayOfТЧзаявка(this);
                }
                IIS.Kursovaya_Gladkov.DetailArrayOfТЧзаявка result = this.fТЧзаявка;
                // *** Start programmer edit section *** (ДокЗаявка.ТЧзаявка Get end)

                // *** End programmer edit section *** (ДокЗаявка.ТЧзаявка Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокЗаявка.ТЧзаявка Set start)

                // *** End programmer edit section *** (ДокЗаявка.ТЧзаявка Set start)
                this.fТЧзаявка = value;
                // *** Start programmer edit section *** (ДокЗаявка.ТЧзаявка Set end)

                // *** End programmer edit section *** (ДокЗаявка.ТЧзаявка Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокЗаявкаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокЗаявкаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокЗаявкаE", typeof(IIS.Kursovaya_Gladkov.ДокЗаявка));
                }
            }
            
            /// <summary>
            /// "ДокЗаявкаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокЗаявкаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокЗаявкаL", typeof(IIS.Kursovaya_Gladkov.ДокЗаявка));
                }
            }
        }
    }
}
