//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Док тех карта.
    /// </summary>
    // *** Start programmer edit section *** (ДокТехКарта CustomAttributes)

    // *** End programmer edit section *** (ДокТехКарта CustomAttributes)
    [AutoAltered()]
    [Caption("Док тех карта")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокТехКартаE", new string[] {
            "ДокЧертеж.НомерЧертежа",
            "ДокЧертеж.Дата as \'Дата\'",
            "СПРоборуд.Наименование",
            "ДокЧертеж.ТЧзаявка.CПРМатериалы"}, Hidden=new string[] {
            "ДокЧертеж.Дата"})]
    [View("ДокТехКартаL", new string[] {
            "ДокЧертеж.НомерЧертежа as \'Номер карты\'",
            "ДокЧертеж.Дата as \'Дата\'",
            "СПРоборуд.Наименование as \'Требуемое оборудование\'",
            "ДокЧертеж.ТЧзаявка.CПРМатериалы as \'Требуемый материал\'"})]
    public class ДокТехКарта : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Kursovaya_Gladkov.СПРоборуд fСПРоборуд;
        
        private IIS.Kursovaya_Gladkov.ДокЧертеж fДокЧертеж;
        
        // *** Start programmer edit section *** (ДокТехКарта CustomMembers)

        // *** End programmer edit section *** (ДокТехКарта CustomMembers)

        
        /// <summary>
        /// Док тех карта.
        /// </summary>
        // *** Start programmer edit section *** (ДокТехКарта.ДокЧертеж CustomAttributes)

        // *** End programmer edit section *** (ДокТехКарта.ДокЧертеж CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокЧертеж"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov.ДокЧертеж ДокЧертеж
        {
            get
            {
                // *** Start programmer edit section *** (ДокТехКарта.ДокЧертеж Get start)

                // *** End programmer edit section *** (ДокТехКарта.ДокЧертеж Get start)
                IIS.Kursovaya_Gladkov.ДокЧертеж result = this.fДокЧертеж;
                // *** Start programmer edit section *** (ДокТехКарта.ДокЧертеж Get end)

                // *** End programmer edit section *** (ДокТехКарта.ДокЧертеж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокТехКарта.ДокЧертеж Set start)

                // *** End programmer edit section *** (ДокТехКарта.ДокЧертеж Set start)
                this.fДокЧертеж = value;
                // *** Start programmer edit section *** (ДокТехКарта.ДокЧертеж Set end)

                // *** End programmer edit section *** (ДокТехКарта.ДокЧертеж Set end)
            }
        }
        
        /// <summary>
        /// Док тех карта.
        /// </summary>
        // *** Start programmer edit section *** (ДокТехКарта.СПРоборуд CustomAttributes)

        // *** End programmer edit section *** (ДокТехКарта.СПРоборуд CustomAttributes)
        [PropertyStorage(new string[] {
                "СПРоборуд"})]
        [NotNull()]
        public virtual IIS.Kursovaya_Gladkov.СПРоборуд СПРоборуд
        {
            get
            {
                // *** Start programmer edit section *** (ДокТехКарта.СПРоборуд Get start)

                // *** End programmer edit section *** (ДокТехКарта.СПРоборуд Get start)
                IIS.Kursovaya_Gladkov.СПРоборуд result = this.fСПРоборуд;
                // *** Start programmer edit section *** (ДокТехКарта.СПРоборуд Get end)

                // *** End programmer edit section *** (ДокТехКарта.СПРоборуд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокТехКарта.СПРоборуд Set start)

                // *** End programmer edit section *** (ДокТехКарта.СПРоборуд Set start)
                this.fСПРоборуд = value;
                // *** Start programmer edit section *** (ДокТехКарта.СПРоборуд Set end)

                // *** End programmer edit section *** (ДокТехКарта.СПРоборуд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокТехКартаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокТехКартаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокТехКартаE", typeof(IIS.Kursovaya_Gladkov.ДокТехКарта));
                }
            }
            
            /// <summary>
            /// "ДокТехКартаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокТехКартаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокТехКартаL", typeof(IIS.Kursovaya_Gladkov.ДокТехКарта));
                }
            }
        }
    }
}
