//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Состояние.
    /// </summary>
    // *** Start programmer edit section *** (Состояние CustomAttributes)

    // *** End programmer edit section *** (Состояние CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СостояниеE", new string[0])]
    [View("СостояниеL", new string[0])]
    public class Состояние : ICSSoft.STORMNET.DataObject
    {
        
        // *** Start programmer edit section *** (Состояние CustomMembers)

        // *** End programmer edit section *** (Состояние CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СостояниеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостояниеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостояниеE", typeof(IIS.Kursovaya_Gladkov.Состояние));
                }
            }
            
            /// <summary>
            /// "СостояниеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СостояниеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СостояниеL", typeof(IIS.Kursovaya_Gladkov.Состояние));
                }
            }
        }
    }
}
