//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// С п р склад.
    /// </summary>
    // *** Start programmer edit section *** (СПРСклад CustomAttributes)

    // *** End programmer edit section *** (СПРСклад CustomAttributes)
    [AutoAltered()]
    [Caption("С п р склад")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СПРСкладE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'"})]
    [View("СПРСкладL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'"})]
    public class СПРСклад : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (СПРСклад CustomMembers)

        // *** End programmer edit section *** (СПРСклад CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (СПРСклад.ID CustomAttributes)

        // *** End programmer edit section *** (СПРСклад.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (СПРСклад.ID Get start)

                // *** End programmer edit section *** (СПРСклад.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (СПРСклад.ID Get end)

                // *** End programmer edit section *** (СПРСклад.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРСклад.ID Set start)

                // *** End programmer edit section *** (СПРСклад.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (СПРСклад.ID Set end)

                // *** End programmer edit section *** (СПРСклад.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СПРСклад.Наименование CustomAttributes)

        // *** End programmer edit section *** (СПРСклад.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СПРСклад.Наименование Get start)

                // *** End programmer edit section *** (СПРСклад.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СПРСклад.Наименование Get end)

                // *** End programmer edit section *** (СПРСклад.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРСклад.Наименование Set start)

                // *** End programmer edit section *** (СПРСклад.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СПРСклад.Наименование Set end)

                // *** End programmer edit section *** (СПРСклад.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СПРСкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СПРСкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СПРСкладE", typeof(IIS.Kursovaya_Gladkov.СПРСклад));
                }
            }
            
            /// <summary>
            /// "СПРСкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СПРСкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СПРСкладL", typeof(IIS.Kursovaya_Gladkov.СПРСклад));
                }
            }
        }
    }
}
