//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// С п роборуд.
    /// </summary>
    // *** Start programmer edit section *** (СПРоборуд CustomAttributes)

    // *** End programmer edit section *** (СПРоборуд CustomAttributes)
    [AutoAltered()]
    [Caption("С п роборуд")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СПРоборудE", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Состояние as \'Состояние\'"})]
    [View("СПРоборудL", new string[] {
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "Состояние as \'Состояние\'"})]
    public class СПРоборуд : ICSSoft.STORMNET.DataObject
    {
        
        private int fID;
        
        private string fНаименование;
        
        private IIS.Kursovaya_Gladkov.Состояние fСостояние;
        
        // *** Start programmer edit section *** (СПРоборуд CustomMembers)

        // *** End programmer edit section *** (СПРоборуд CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (СПРоборуд.ID CustomAttributes)

        // *** End programmer edit section *** (СПРоборуд.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (СПРоборуд.ID Get start)

                // *** End programmer edit section *** (СПРоборуд.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (СПРоборуд.ID Get end)

                // *** End programmer edit section *** (СПРоборуд.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРоборуд.ID Set start)

                // *** End programmer edit section *** (СПРоборуд.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (СПРоборуд.ID Set end)

                // *** End programmer edit section *** (СПРоборуд.ID Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СПРоборуд.Наименование CustomAttributes)

        // *** End programmer edit section *** (СПРоборуд.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СПРоборуд.Наименование Get start)

                // *** End programmer edit section *** (СПРоборуд.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СПРоборуд.Наименование Get end)

                // *** End programmer edit section *** (СПРоборуд.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРоборуд.Наименование Set start)

                // *** End programmer edit section *** (СПРоборуд.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СПРоборуд.Наименование Set end)

                // *** End programmer edit section *** (СПРоборуд.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Состояние.
        /// </summary>
        // *** Start programmer edit section *** (СПРоборуд.Состояние CustomAttributes)

        // *** End programmer edit section *** (СПРоборуд.Состояние CustomAttributes)
        public virtual IIS.Kursovaya_Gladkov.Состояние Состояние
        {
            get
            {
                // *** Start programmer edit section *** (СПРоборуд.Состояние Get start)

                // *** End programmer edit section *** (СПРоборуд.Состояние Get start)
                IIS.Kursovaya_Gladkov.Состояние result = this.fСостояние;
                // *** Start programmer edit section *** (СПРоборуд.Состояние Get end)

                // *** End programmer edit section *** (СПРоборуд.Состояние Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРоборуд.Состояние Set start)

                // *** End programmer edit section *** (СПРоборуд.Состояние Set start)
                this.fСостояние = value;
                // *** Start programmer edit section *** (СПРоборуд.Состояние Set end)

                // *** End programmer edit section *** (СПРоборуд.Состояние Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СПРоборудE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СПРоборудE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СПРоборудE", typeof(IIS.Kursovaya_Gladkov.СПРоборуд));
                }
            }
            
            /// <summary>
            /// "СПРоборудL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СПРоборудL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СПРоборудL", typeof(IIS.Kursovaya_Gladkov.СПРоборуд));
                }
            }
        }
    }
}
