//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya_Gladkov
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// С п р клиент.
    /// </summary>
    // *** Start programmer edit section *** (СПРКлиент CustomAttributes)

    // *** End programmer edit section *** (СПРКлиент CustomAttributes)
    [AutoAltered()]
    [Caption("С п р клиент")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СПРКлиентE", new string[] {
            "РасСчет as \'Рас счет\'",
            "Телефон as \'Телефон\'",
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "ФИООтветст as \'Ф и о ответст\'",
            "ИНН as \'ИНН\'",
            "Почта as \'Почта\'",
            "Банк as \'Банк\'"})]
    [View("СПРКлиентL", new string[] {
            "РасСчет as \'Рас счет\'",
            "Телефон as \'Телефон\'",
            "ID as \'ID\'",
            "Наименование as \'Наименование\'",
            "ФИООтветст as \'Ф и о ответст\'",
            "ИНН as \'ИНН\'",
            "Почта as \'Почта\'",
            "Банк as \'Банк\'"})]
    public class СПРКлиент : ICSSoft.STORMNET.DataObject
    {
        
        private int fРасСчет;
        
        private int fТелефон;
        
        private int fID;
        
        private string fНаименование;
        
        private string fФИООтветст;
        
        private int fИНН;
        
        private string fПочта;
        
        private string fБанк;
        
        // *** Start programmer edit section *** (СПРКлиент CustomMembers)

        // *** End programmer edit section *** (СПРКлиент CustomMembers)

        
        /// <summary>
        /// ID.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.ID CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.ID CustomAttributes)
        public virtual int ID
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.ID Get start)

                // *** End programmer edit section *** (СПРКлиент.ID Get start)
                int result = this.fID;
                // *** Start programmer edit section *** (СПРКлиент.ID Get end)

                // *** End programmer edit section *** (СПРКлиент.ID Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.ID Set start)

                // *** End programmer edit section *** (СПРКлиент.ID Set start)
                this.fID = value;
                // *** Start programmer edit section *** (СПРКлиент.ID Set end)

                // *** End programmer edit section *** (СПРКлиент.ID Set end)
            }
        }
        
        /// <summary>
        /// Банк.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.Банк CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.Банк CustomAttributes)
        [StrLen(255)]
        public virtual string Банк
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.Банк Get start)

                // *** End programmer edit section *** (СПРКлиент.Банк Get start)
                string result = this.fБанк;
                // *** Start programmer edit section *** (СПРКлиент.Банк Get end)

                // *** End programmer edit section *** (СПРКлиент.Банк Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.Банк Set start)

                // *** End programmer edit section *** (СПРКлиент.Банк Set start)
                this.fБанк = value;
                // *** Start programmer edit section *** (СПРКлиент.Банк Set end)

                // *** End programmer edit section *** (СПРКлиент.Банк Set end)
            }
        }
        
        /// <summary>
        /// ИНН.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.ИНН CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.ИНН CustomAttributes)
        public virtual int ИНН
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.ИНН Get start)

                // *** End programmer edit section *** (СПРКлиент.ИНН Get start)
                int result = this.fИНН;
                // *** Start programmer edit section *** (СПРКлиент.ИНН Get end)

                // *** End programmer edit section *** (СПРКлиент.ИНН Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.ИНН Set start)

                // *** End programmer edit section *** (СПРКлиент.ИНН Set start)
                this.fИНН = value;
                // *** Start programmer edit section *** (СПРКлиент.ИНН Set end)

                // *** End programmer edit section *** (СПРКлиент.ИНН Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.Наименование CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.Наименование Get start)

                // *** End programmer edit section *** (СПРКлиент.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (СПРКлиент.Наименование Get end)

                // *** End programmer edit section *** (СПРКлиент.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.Наименование Set start)

                // *** End programmer edit section *** (СПРКлиент.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (СПРКлиент.Наименование Set end)

                // *** End programmer edit section *** (СПРКлиент.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Почта.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.Почта CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.Почта CustomAttributes)
        [StrLen(255)]
        public virtual string Почта
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.Почта Get start)

                // *** End programmer edit section *** (СПРКлиент.Почта Get start)
                string result = this.fПочта;
                // *** Start programmer edit section *** (СПРКлиент.Почта Get end)

                // *** End programmer edit section *** (СПРКлиент.Почта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.Почта Set start)

                // *** End programmer edit section *** (СПРКлиент.Почта Set start)
                this.fПочта = value;
                // *** Start programmer edit section *** (СПРКлиент.Почта Set end)

                // *** End programmer edit section *** (СПРКлиент.Почта Set end)
            }
        }
        
        /// <summary>
        /// РасСчет.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.РасСчет CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.РасСчет CustomAttributes)
        public virtual int РасСчет
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.РасСчет Get start)

                // *** End programmer edit section *** (СПРКлиент.РасСчет Get start)
                int result = this.fРасСчет;
                // *** Start programmer edit section *** (СПРКлиент.РасСчет Get end)

                // *** End programmer edit section *** (СПРКлиент.РасСчет Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.РасСчет Set start)

                // *** End programmer edit section *** (СПРКлиент.РасСчет Set start)
                this.fРасСчет = value;
                // *** Start programmer edit section *** (СПРКлиент.РасСчет Set end)

                // *** End programmer edit section *** (СПРКлиент.РасСчет Set end)
            }
        }
        
        /// <summary>
        /// Телефон.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.Телефон CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.Телефон CustomAttributes)
        public virtual int Телефон
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.Телефон Get start)

                // *** End programmer edit section *** (СПРКлиент.Телефон Get start)
                int result = this.fТелефон;
                // *** Start programmer edit section *** (СПРКлиент.Телефон Get end)

                // *** End programmer edit section *** (СПРКлиент.Телефон Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.Телефон Set start)

                // *** End programmer edit section *** (СПРКлиент.Телефон Set start)
                this.fТелефон = value;
                // *** Start programmer edit section *** (СПРКлиент.Телефон Set end)

                // *** End programmer edit section *** (СПРКлиент.Телефон Set end)
            }
        }
        
        /// <summary>
        /// ФИООтветст.
        /// </summary>
        // *** Start programmer edit section *** (СПРКлиент.ФИООтветст CustomAttributes)

        // *** End programmer edit section *** (СПРКлиент.ФИООтветст CustomAttributes)
        [StrLen(255)]
        public virtual string ФИООтветст
        {
            get
            {
                // *** Start programmer edit section *** (СПРКлиент.ФИООтветст Get start)

                // *** End programmer edit section *** (СПРКлиент.ФИООтветст Get start)
                string result = this.fФИООтветст;
                // *** Start programmer edit section *** (СПРКлиент.ФИООтветст Get end)

                // *** End programmer edit section *** (СПРКлиент.ФИООтветст Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СПРКлиент.ФИООтветст Set start)

                // *** End programmer edit section *** (СПРКлиент.ФИООтветст Set start)
                this.fФИООтветст = value;
                // *** Start programmer edit section *** (СПРКлиент.ФИООтветст Set end)

                // *** End programmer edit section *** (СПРКлиент.ФИООтветст Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СПРКлиентE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СПРКлиентE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СПРКлиентE", typeof(IIS.Kursovaya_Gladkov.СПРКлиент));
                }
            }
            
            /// <summary>
            /// "СПРКлиентL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СПРКлиентL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СПРКлиентL", typeof(IIS.Kursovaya_Gladkov.СПРКлиент));
                }
            }
        }
    }
}
